<script lang="ts">
  // THE JOIN PANEL: the console's answer to "how do these thirty people get in".
  //
  // It opens IN PLACE as a rail beside the console (the persistent-layout law,
  // docs/decisions/2026-08-16-persistent-layout-and-pregame-rework.md) - never a page, never a
  // modal: the roster keeps filling and the board keeps running behind it while a host holds the
  // laptop up to the room.
  //
  // THE STREAMER-MODE BOUNDARY, AND IT IS THE OPPOSITE OF THE DISPLAY'S.
  // `settings.hideJoinCode` means "stop broadcasting the code on SHARED surfaces"
  // (docs/decisions/2026-08-14-room-controls-and-staging.md). The display is the shared surface,
  // so it drops the code, the QR and the join URL from its MARKUP entirely. This console is the
  // host's own private screen - it is where the answers to every clue live, so a room that can
  // read this panel can already read the answers - and a host in streamer mode still has to get
  // people into the room. So the console keeps the code, the QR and the link, and says out loud
  // that they are not on the big screen. Hiding it here would protect nothing and would leave a
  // streaming host with no way to admit a latecomer at all.
  import { renderSVG } from "uqr";
  import {
    copyJoinLink,
    joinUrlFor,
    joinUrlLabel,
    shareJoinLink,
    shareOutcomeLine,
  } from "#lib/room/join-share.ts";
  import type { ShareTarget } from "#lib/room/join-share.ts";
  import type { RoomStore } from "#lib/room/room-store.ts";

  type Props = {
    store: RoomStore;
    /** Origin for the join URL; defaults to this window's at runtime (as the display does). */
    joinOrigin?: string | null;
    /** Injected for tests; the browser's own navigator otherwise. */
    shareTarget?: ShareTarget | null;
    /** Start in the hold-it-up-to-the-room state - what the fullscreen tests render. */
    expanded?: boolean;
    onClose?: (() => void) | null;
  };
  let {
    store,
    joinOrigin = null,
    shareTarget = null,
    expanded = false,
    onClose = null,
  }: Props = $props();

  const view = $derived(store.view);
  const joinUrl = $derived(
    joinUrlFor(joinOrigin ?? (typeof location === "undefined" ? null : location.origin), view.roomCode),
  );
  // Trusted @html downstream: generated by uqr from our own join URL, never from user input.
  const qrSvg = $derived(renderSVG(joinUrl, { border: 2 }));
  const hiddenOnShared = $derived(view.settings.hideJoinCode);
  const playerCount = $derived(view.roster.players.length);

  // svelte-ignore state_referenced_locally - the prop is the INITIAL value only.
  let showBig = $state(expanded);
  let shareLine = $state<string | null>(null);
  let panelElement = $state<HTMLElement | null>(null);

  function target(): ShareTarget | null {
    if (shareTarget !== null) return shareTarget;
    return (globalThis as { navigator?: ShareTarget }).navigator ?? null;
  }

  async function share(): Promise<void> {
    shareLine = shareOutcomeLine(await shareJoinLink(target(), { roomCode: view.roomCode, joinUrl }));
  }

  async function copy(): Promise<void> {
    shareLine = shareOutcomeLine(await copyJoinLink(target(), joinUrl));
  }

  /**
   * "Hold the laptop up to the room": the SAME panel grows to fill the screen - one element
   * changing state, not a second screen (the persistent-layout law again). The real Fullscreen
   * API is asked for on top, best-effort, because a projector-lit room reads a borderless window
   * better; a browser that refuses it (permissions policy, iframe, Safari on a non-video element)
   * loses nothing, since the CSS state is what actually does the work.
   */
  function toggleBig(): void {
    showBig = !showBig;
    const element = panelElement;
    if (element === null) return;
    if (showBig) void element.requestFullscreen?.().catch(() => undefined);
    else void document.exitFullscreen?.().catch(() => undefined);
  }
</script>

<aside
  class="join-panel"
  class:big={showBig}
  aria-label="How people join"
  bind:this={panelElement}
>
  <header class="panel-head">
    <h2>How people join</h2>
    <div class="head-actions">
      <button type="button" class="chip" aria-pressed={showBig} onclick={toggleBig}>
        {showBig ? "Done" : "Show fullscreen"}
      </button>
      {#if onClose !== null && !showBig}
        <button type="button" class="chip" onclick={onClose}>Close</button>
      {/if}
    </div>
  </header>

  {#if hiddenOnShared}
    <!-- Streamer mode, stated rather than obeyed: this is the host's own screen. -->
    <p class="streamer-note">
      <span class="badge">Streamer mode</span>
      Hidden on the game screen and every shared surface. Still here, because this console is yours.
    </p>
  {/if}

  <p class="code-label">Room code</p>
  <p class="room-code">{view.roomCode}</p>

  <div class="qr-holder" aria-label="Join QR code">
    <!-- Trusted @html: uqr over our own join URL (see the script comment). -->
    {@html qrSvg}
  </div>

  <p class="join-url">{joinUrlLabel(joinUrl)}</p>

  <div class="actions">
    <!-- Share sheet first: phone-to-phone is the natural path into a group chat, and it is the
         only one that reaches somebody who is not in the room (src/lib/room/join-share.ts). -->
    <button type="button" class="chip primary" onclick={() => void share()}>Share link</button>
    <button type="button" class="chip" onclick={() => void copy()}>Copy link</button>
  </div>

  <!-- Reserved so an outcome sentence changes words rather than positions (the reserved-space
       corollary of the persistent-layout law). -->
  <p class="share-line" role="status">{shareLine ?? ""}</p>

  <p class="joined-count">
    {playerCount}
    {playerCount === 1 ? "player" : "players"} in
  </p>
</aside>

<style>
  /* A rail beside the console, exactly like the cog: opening it narrows the console rather than
     covering it, so the roster and the board stay live while people are arriving. */
  .join-panel {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 0.5rem;
    width: 20rem;
    max-height: calc(100dvh - 2rem);
    overflow-y: auto;
    padding: 0.8rem 0.9rem 1.2rem;
    border: 1px solid var(--surface-border);
    border-radius: var(--board-radius);
    background: var(--surface-raised);
    color: var(--surface-text);
  }

  .panel-head {
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 0.5rem;
    width: 100%;
  }

  .panel-head h2 {
    margin: 0;
    font-family: var(--font-chrome);
    text-transform: uppercase;
    letter-spacing: 0.08em;
    font-size: 1em;
  }

  .head-actions {
    display: flex;
    gap: 0.3rem;
  }

  .streamer-note {
    margin: 0;
    font-family: var(--font-chrome);
    font-size: 0.72em;
    line-height: 1.4;
    color: var(--surface-text-muted);
  }

  .badge {
    display: inline-block;
    margin-right: 0.35rem;
    font-size: 0.9em;
    text-transform: uppercase;
    letter-spacing: 0.1em;
    border: 1px solid currentColor;
    border-radius: 999px;
    padding: 0.05rem 0.4rem;
  }

  .code-label {
    margin: 0;
    font-family: var(--font-chrome);
    font-size: 0.7em;
    text-transform: uppercase;
    letter-spacing: 0.16em;
    color: var(--surface-text-muted);
  }

  /* The code is the one thing a room reads off a laptop held above someone's head, so it is
     sized like a board value rather than like chrome. */
  .room-code {
    margin: 0;
    font-family: var(--font-values);
    font-size: 3.4em;
    line-height: 0.95;
    letter-spacing: 0.12em;
    color: var(--board-value-color);
  }

  /* Scannable from a few feet: a phone camera needs roughly a hand's width of QR at 2 m, so the
     module is sized in rem (not a percentage of a rail that could be narrow) and grows with the
     console's type scale like everything else here. */
  .qr-holder {
    display: flex;
    padding: 0.5rem;
    background: #ffffff;
    border-radius: var(--board-radius);
  }

  .qr-holder :global(svg) {
    display: block;
    width: min(14rem, 70vw);
    height: auto;
  }

  .join-url {
    margin: 0;
    font-family: var(--font-chrome);
    font-size: 0.95em;
    text-align: center;
    overflow-wrap: anywhere;
  }

  .actions {
    display: flex;
    flex-wrap: wrap;
    justify-content: center;
    gap: 0.35rem;
  }

  .share-line {
    margin: 0;
    min-height: 1.2em;
    font-family: var(--font-chrome);
    font-size: 0.75em;
    color: var(--surface-text-muted);
  }

  .joined-count {
    margin: 0;
    font-family: var(--font-chrome);
    font-size: 0.8em;
    color: var(--surface-text-muted);
  }

  .chip {
    font-family: var(--font-chrome);
    font-size: 0.8em;
    text-transform: uppercase;
    letter-spacing: 0.06em;
    padding: 0.3rem 0.6rem;
    border: 1px solid var(--surface-border);
    border-radius: var(--board-radius);
    background: transparent;
    color: inherit;
    cursor: pointer;
  }

  .chip.primary {
    border-color: var(--accent);
    color: var(--accent);
  }

  /* HOLD IT UP TO THE ROOM. The same element, filling the screen - the code and the QR sized
     against the shorter viewport axis so a laptop turned around is legible from the back row. */
  .join-panel.big {
    position: fixed;
    inset: 0;
    z-index: 60;
    width: auto;
    max-height: none;
    justify-content: center;
    gap: 1.2rem;
    background: var(--surface-page);
  }

  .join-panel.big .room-code {
    font-size: min(22vh, 22vw);
  }

  .join-panel.big .qr-holder :global(svg) {
    width: min(46vh, 46vw);
  }

  .join-panel.big .join-url {
    font-size: min(4vh, 4vw);
  }

  @media (max-width: 64rem) {
    .join-panel {
      width: auto;
    }
  }
</style>
