// Typed access to the generated avatar manifest. avatar-manifest.json is written by
// tools/avatar-bake (never by hand - see that package's README for how/when to re-bake); this
// module is the only place shipped code should read it through, so the JSON shape is asserted
// once here and the gate test (avatar-manifest.gate.test.ts) holds the file to it.
//
// The accent list IS the player-accent palette: defined once in
// tools/avatar-bake/src/accent-palette.mjs, copied verbatim into the manifest at bake time.
// Components never hard-code accent hexes.
import manifestJson from "#lib/avatars/avatar-manifest.json";

export type AvatarKind = "pet" | "human";

export type AvatarAccent = {
  /** Stable accent id; also the accent segment of sprite filenames (`{avatar}--{accent}.webp`). */
  id: string;
  /** The accent color itself - chip backings, selection rings, roster tinting. */
  hex: string;
};

/** The three animation roles every shipped model exposes (tools/avatar-bake/src/roster.mjs). */
export type AvatarClipRole = "idle" | "walk" | "celebrate";

export type AvatarSheet = {
  /** Horizontal filmstrip under `basePath`: manifest.sheet.frames square frames, left to right. */
  file: string;
  /** Which pack clip was rendered - "walk" normally, an idle clip where a pack lacks one. */
  clip: string;
};

export type AvatarModel = {
  /** Trimmed GLB filename under `modelPath`. */
  file: string;
  /** The pack's shared palette texture (also under `modelPath`) - the recolor's input image. */
  colormap: string;
  /** Extra models composited at the same origin (Ada's wheelchair), also under `modelPath`. */
  props: readonly string[];
  /** Role -> the pack's own clip name. Shipped code names roles, never Kenney clip names. */
  clips: Record<AvatarClipRole, string>;
  /** Colormap cells the player accent replaces - the runtime recolor's targets. */
  recolorTargets: readonly string[];
  /** Per-avatar RGB match distance; null means palette-recolor.ts's default. */
  tolerance: number | null;
};

export type AvatarEntry = {
  id: string;
  kind: AvatarKind;
  /** Picker label and sprite alt text. */
  displayName: string;
  /** accent id -> sprite filename under `basePath`. */
  sprites: Record<string, string>;
  /** The animated tier (join preview, lobby card) - one sheet per avatar, its own colors. */
  sheet: AvatarSheet;
  /** The live tier (display diorama only) - everything needed to instance and recolor a model. */
  model: AvatarModel;
};

export type AvatarManifest = {
  version: number;
  /** Square sprite edge in px (rendered size; display sizes are a styling concern). */
  spriteSize: number;
  /** Public URL prefix the sprite and sheet filenames resolve against. */
  basePath: string;
  /** Public URL prefix for GLBs and colormaps. Only the display route ever fetches these. */
  modelPath: string;
  /** Sheet geometry, shared by every avatar: N square frames of frameSize px, horizontal. */
  sheet: { frames: number; frameSize: number };
  accents: readonly AvatarAccent[];
  avatars: readonly AvatarEntry[];
};

// Narrowing assertion (JSON's `kind: string` -> the union): the gate test validates the
// actual contents, and the version check catches a manifest generated by an older/newer bake.
export const avatarManifest = manifestJson as AvatarManifest;

if (avatarManifest.version !== 2) {
  throw new Error(
    `avatar-manifest.json version ${avatarManifest.version} does not match this loader (2) - re-bake via tools/avatar-bake`,
  );
}

/** Public URL of one avatar sprite; throws on an unknown accent rather than 404ing quietly. */
export function avatarSpriteUrl(avatar: AvatarEntry, accentId: string): string {
  const fileName = avatar.sprites[accentId];
  if (fileName === undefined) {
    throw new Error(`avatar "${avatar.id}" has no sprite for accent "${accentId}"`);
  }
  return avatarManifest.basePath + fileName;
}

/** Public URL of one avatar's walk-cycle filmstrip. */
export function avatarSheetUrl(avatar: AvatarEntry): string {
  return avatarManifest.basePath + avatar.sheet.file;
}

/**
 * Public URL of a file under the model path (a GLB or a colormap PNG). Display-route only:
 * every caller sits behind the diorama's dynamic import, so no phone ever resolves one.
 */
export function avatarModelUrl(fileName: string): string {
  return avatarManifest.modelPath + fileName;
}

/** Look up an avatar by id - the roster carries ids, the manifest carries everything else. */
export function avatarById(avatarId: string | null): AvatarEntry | null {
  if (avatarId === null) return null;
  return avatarManifest.avatars.find((entry) => entry.id === avatarId) ?? null;
}

/** Look up an accent by id, falling back to the first palette entry (the default accent). */
export function accentById(accentId: string | null): AvatarAccent {
  const found = avatarManifest.accents.find((entry) => entry.id === accentId);
  const fallback = avatarManifest.accents[0];
  if (fallback === undefined) throw new Error("avatar manifest has an empty accent palette");
  return found ?? fallback;
}
