// Typed access to the generated avatar manifest. avatar-manifest.json is written by
// tools/avatar-bake (never by hand - see that package's README for how/when to re-bake); this
// module is the only place shipped code should read it through, so the JSON shape is asserted
// once here and the gate test (avatar-manifest.gate.test.ts) holds the file to it.
//
// The accent list IS the player-accent palette: defined once in
// tools/avatar-bake/src/accent-palette.mjs, copied verbatim into the manifest at bake time.
// Components never hard-code accent hexes.
import manifestJson from "#lib/avatars/avatar-manifest.json";

export type AvatarKind = "pet" | "human";

export type AvatarAccent = {
  /** Stable accent id; also the accent segment of sprite filenames (`{avatar}--{accent}.webp`). */
  id: string;
  /** The accent color itself - chip backings, selection rings, roster tinting. */
  hex: string;
};

export type AvatarEntry = {
  id: string;
  kind: AvatarKind;
  /** Picker label and sprite alt text. */
  displayName: string;
  /** accent id -> sprite filename under `basePath`. */
  sprites: Record<string, string>;
};

export type AvatarManifest = {
  version: number;
  /** Square sprite edge in px (rendered size; display sizes are a styling concern). */
  spriteSize: number;
  /** Public URL prefix the sprite filenames resolve against. */
  basePath: string;
  accents: readonly AvatarAccent[];
  avatars: readonly AvatarEntry[];
};

// Narrowing assertion (JSON's `kind: string` -> the union): the gate test validates the
// actual contents, and the version check catches a manifest generated by an older/newer bake.
export const avatarManifest = manifestJson as AvatarManifest;

if (avatarManifest.version !== 1) {
  throw new Error(
    `avatar-manifest.json version ${avatarManifest.version} does not match this loader (1) - re-bake via tools/avatar-bake`,
  );
}

/** Public URL of one avatar sprite; throws on an unknown accent rather than 404ing quietly. */
export function avatarSpriteUrl(avatar: AvatarEntry, accentId: string): string {
  const fileName = avatar.sprites[accentId];
  if (fileName === undefined) {
    throw new Error(`avatar "${avatar.id}" has no sprite for accent "${accentId}"`);
  }
  return avatarManifest.basePath + fileName;
}
