// The MODEL tier of the baked avatar set: what the display's diorama needs to instance a
// Kenney GLB and tint it to a player's accent (docs/decisions/2026-08-14-avatars-in-motion.md,
// tier 3). Generated by tools/avatar-bake alongside the sprite manifest, never edited by hand.
//
// Separate from avatar-manifest.ts ON PURPOSE, and the separation is load-bearing: the sprite
// manifest is a static import on every avatar surface including the phone's join and lobby
// screens, while THIS module is imported only by src/lib/diorama/diorama-scene.ts - which is
// itself only reached through a dynamic import. So this JSON rides the diorama's own chunk,
// the display route is the only thing that ever downloads it, and the phone's bundle does not
// move. Importing this file from anywhere outside src/lib/diorama would silently undo that;
// the guardrail gate (src/lib/diorama/motion-guardrails.gate.test.ts) checks that it does not.
import modelsJson from "#lib/avatars/avatar-models.json";

/** The three animation roles every shipped model exposes (tools/avatar-bake/src/roster.mjs). */
export type AvatarClipRole = "idle" | "walk" | "celebrate";

export type AvatarModel = {
  /** Manifest avatar id this model belongs to. */
  id: string;
  /** Trimmed GLB filename under `modelPath`. */
  file: string;
  /** The pack's shared palette texture (also under `modelPath`) - the recolor's input image. */
  colormap: string;
  /** Extra models composited at the same origin (Ada's wheelchair), also under `modelPath`. */
  props: readonly string[];
  /** Role -> the pack's own clip name. Shipped code names roles, never Kenney clip names. */
  clips: Record<AvatarClipRole, string>;
  /** Colormap cells the player accent replaces - the runtime recolor's targets. */
  recolorTargets: readonly string[];
  /** Per-avatar RGB match distance; null means palette-recolor.ts's default. */
  tolerance: number | null;
};

export type AvatarModelManifest = {
  version: number;
  /** Public URL prefix for GLBs and colormaps. Only the display route ever fetches these. */
  modelPath: string;
  avatars: readonly AvatarModel[];
};

export const avatarModelManifest = modelsJson as AvatarModelManifest;

if (avatarModelManifest.version !== 1) {
  throw new Error(
    `avatar-models.json version ${avatarModelManifest.version} does not match this loader (1) - re-bake via tools/avatar-bake`,
  );
}

/** Public URL of a file under the model path (a GLB or a colormap PNG). */
export function avatarModelUrl(fileName: string): string {
  return avatarModelManifest.modelPath + fileName;
}

/** The model tier for one avatar id, or null when the roster carries an id we do not ship. */
export function avatarModelById(avatarId: string): AvatarModel | null {
  return avatarModelManifest.avatars.find((entry) => entry.id === avatarId) ?? null;
}
